### ISSUE TITLE
[Bug] installing comfyui-easyapi-nodes causes reloaded ComfyUI tabs to freeze. 安装 comfyui-easyapi-nodes 会导致重新加载的 ComfyUI 选项卡冻结。

### ISSUE THREAD

**Issue by ricardofeynman** [lldacing/comfyui-easyapi-nodes#1]
谢谢你。我真的希望它能对一个项目有所帮助。我有兴趣测试。 不幸的是，目前当我在浏览器中按重新加载 （firefox v121 linux mint） 时，重新加载需要很长时间，然后唯一有效的控件是 ctrl + / ctrl - 但除此之外，流程图完全冻结并保持冻结状态。 如果打开了多个工作流选项卡，前提是它们不是通过浏览器按钮重新加载的，它们仍然有效。

Original:

Thanks for this. I'm really hoping it could help for a project. I'm interested to test.

Unfortunately at the moment, when I press reload in the browser (firefox v121 linux mint), it takes a very long time to reload, then the only controls that work are ctrl + / ctrl - but otherwise the flowchart is completely frozen and remains frozen. 

If multiple workflow tabs are open, provided that they are not also reloaded via the browser button, they still work.

**Comment by lldacing** [comment]
适合api方式调用，因为把图片转成了base64，对浏览器来说base64字符串太长了，加载到内存中会比较卡

**Comment by lldacing** [comment]
如果有oss图片服务器或服务接口的话，可以自定义节点从远程服务器加载和上传图片，我这里现在加了LoadImageFromURL和LoadMaskFromURL用来加载图片和遮罩，至于上传，需要你自己实现，我只是把在公司开发过程中新增的一些通用的节点提交到了这里

**Comment by ricardofeynman** [comment]
Thank you for the information. This should maybe be added to the Readme.

谢谢你的信息。这也许应该添加到自述文件中。
