### ISSUE TITLE
comfyUI安装了插件还是无法使用save easyapi as 选项呢

### ISSUE THREAD

**Issue by jwmemail** [lldacing/comfyui-easyapi-nodes#2]
is:issue is:open 请问下，为啥comfyUI安装了这个插件还是无法使用save easyapi as 选项呢？save那里还是是能保存为workflow

**Comment by lldacing** [comment]
![image](https://github.com/lldacing/comfyui-easyapi-nodes/assets/43737696/4b9bd4a6-6360-4754-8626-f3a1faa24a2b)

需要在设置中打开开发者模式菜单
